export const projects = [
  {
    title: 'Crypto Bag - Cryptocurrency Service',
    description: "A cryptocurrency website that offers real-time data, news, and exchange information. Users can connect to MetaMask wallet to send cryptocurrency to a different address on the Ethereum blockchain. ",
      image: '/images/crypto_bag.png',
      tags: ['React', 'Redux Toolkit','API','Ant Design'],
    visit: 'https://cryptobag.netlify.app/',
    id: 0,
  },
  {
    title: 'Travel Advisor',
    description: "Using React, Material UI, Google map, and autocomplete location API, I built a travel advisor web application. The App allows users to  search for restaurants, attraction, and hotels based on the specified location or the brower's location (by default). The app utilizes Google's autocomplete seach API for the search bar.",
      image: '/images/travel_advisor.png',
      tags: ['React', 'REST API', 'Google Map', 'Material UI'],
    source: 'https://github.com/vanhuycx/travel_advisor_website',
    visit: 'https://van-travel-advisor.netlify.app/',
    id: 1,
  },
  {
    title: 'Krypt - Web 3.0 Blockchain Application',
    description:"I build a Web 3.0 Application - from start to finish - using Web 3.0 methodologies, React, Solidity, and Metamask wallet",
    image: '/images/krypt.png',
    tags: ['React', 'Web 3.0','Solidity','Blockchain Smart Contract','MetaMask'],
    source: 'https://github.com/vanhuycx/krypto_website',
    visit: 'https://van-krypt.netlify.app/',
    id: 2,
  },
  {
    title: 'Tetris game',
    description: "This is a code repository for the corresponding Tetris game. The simple Tetris game is built with React, Redux, and CSS.",
    tags: ['React', 'Redux', 'CSS'],
      image: '/images/tetris.png',
    source: 'https://github.com/vanhuycx/tetris_game',
    visit: 'https://van-tetris.netlify.app/',
    id: 3,
  },
  {
    title: 'Boston Housing Prediction',
    description: "This app applies machine learning to predict house price based on provided criteria. Random Forest Regressor is the model used in this context.",
    tags: ['Machine learning', 'Price Prediction', 'Heroku'],
    image: '/images/boston_housing_prediction.png',
    source: 'https://github.com/vanhuycx/boston-houseprice-prediction',
    visit: 'https://boston-houseprice-prediction.herokuapp.com/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey in the U.S.A', },
  { year: 2018, text: 'Apply for IT Associate program at Bunker Hill Community collegee', },
  { year: 2019, text: 'Internship at Eaton Vance financial managenent.', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Begin to create websites using Javascript and React framework', },
  { year: 2022, text: 'Continue to develop skill in IT. Graduating from UMass Boston - May 2022', },
];